//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from functional.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class functionalLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		WS=10, INT=11, ID=12, STR=13, UNTERMINATEDSTR=14, PLUS=15, MINUS=16, TIMES=17, 
		LPAREN=18, RPAREN=19, EQUALS=20, DBLCOLON=21, ARROW=22, AND=23, OR=24, 
		LBRACK=25, RBRACK=26, COMMA=27, JOIN=28, DOT=29, NL=30;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"WS", "INT", "ID", "STR", "UNTERMINATEDSTR", "PLUS", "MINUS", "TIMES", 
		"LPAREN", "RPAREN", "EQUALS", "DBLCOLON", "ARROW", "AND", "OR", "LBRACK", 
		"RBRACK", "COMMA", "JOIN", "DOT", "NL"
	};


	public functionalLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public functionalLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'module'", "'import'", "'include'", "'external'", "'type'", "'List'", 
		"'where'", "'_'", "'nil'", null, null, null, null, null, "'+'", "'-'", 
		"'*'", "'('", "')'", "'='", "'::'", "'->'", "'&'", "'|'", "'['", "']'", 
		"','", "':'", "'.'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, "WS", "INT", 
		"ID", "STR", "UNTERMINATEDSTR", "PLUS", "MINUS", "TIMES", "LPAREN", "RPAREN", 
		"EQUALS", "DBLCOLON", "ARROW", "AND", "OR", "LBRACK", "RBRACK", "COMMA", 
		"JOIN", "DOT", "NL"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "functional.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static functionalLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', ' ', '\xBB', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\v', '\x6', '\v', 'v', '\n', '\v', '\r', '\v', '\xE', 
		'\v', 'w', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x6', '\f', '}', '\n', 
		'\f', '\r', '\f', '\xE', '\f', '~', '\x3', '\r', '\x3', '\r', '\a', '\r', 
		'\x83', '\n', '\r', '\f', '\r', '\xE', '\r', '\x86', '\v', '\r', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x5', '\xF', '\x90', '\n', '\xF', 
		'\a', '\xF', '\x92', '\n', '\xF', '\f', '\xF', '\xE', '\xF', '\x95', '\v', 
		'\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x6', '\x1F', '\xB8', 
		'\n', '\x1F', '\r', '\x1F', '\xE', '\x1F', '\xB9', '\x2', '\x2', ' ', 
		'\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', 
		'\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', 
		'\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', 
		'#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', 
		'\x18', '/', '\x19', '\x31', '\x1A', '\x33', '\x1B', '\x35', '\x1C', '\x37', 
		'\x1D', '\x39', '\x1E', ';', '\x1F', '=', ' ', '\x3', '\x2', '\a', '\x5', 
		'\x2', '\v', '\v', '\xF', '\xF', '\"', '\"', '\x3', '\x2', '\x32', ';', 
		'\x4', '\x2', '\x43', '\\', '\x63', '|', '\x6', '\x2', '\x32', ';', '\x43', 
		'\\', '\x61', '\x61', '\x63', '|', '\x6', '\x2', '\f', '\f', '\xF', '\xF', 
		'$', '$', '^', '^', '\x2', '\xC1', '\x2', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', 
		'\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x39', '\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x3', '?', '\x3', '\x2', '\x2', 
		'\x2', '\x5', '\x46', '\x3', '\x2', '\x2', '\x2', '\a', 'M', '\x3', '\x2', 
		'\x2', '\x2', '\t', 'U', '\x3', '\x2', '\x2', '\x2', '\v', '^', '\x3', 
		'\x2', '\x2', '\x2', '\r', '\x63', '\x3', '\x2', '\x2', '\x2', '\xF', 
		'h', '\x3', '\x2', '\x2', '\x2', '\x11', 'n', '\x3', '\x2', '\x2', '\x2', 
		'\x13', 'p', '\x3', '\x2', '\x2', '\x2', '\x15', 'u', '\x3', '\x2', '\x2', 
		'\x2', '\x17', '|', '\x3', '\x2', '\x2', '\x2', '\x19', '\x80', '\x3', 
		'\x2', '\x2', '\x2', '\x1B', '\x87', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'\x8A', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x96', '\x3', '\x2', '\x2', 
		'\x2', '!', '\x98', '\x3', '\x2', '\x2', '\x2', '#', '\x9A', '\x3', '\x2', 
		'\x2', '\x2', '%', '\x9C', '\x3', '\x2', '\x2', '\x2', '\'', '\x9E', '\x3', 
		'\x2', '\x2', '\x2', ')', '\xA0', '\x3', '\x2', '\x2', '\x2', '+', '\xA2', 
		'\x3', '\x2', '\x2', '\x2', '-', '\xA5', '\x3', '\x2', '\x2', '\x2', '/', 
		'\xA8', '\x3', '\x2', '\x2', '\x2', '\x31', '\xAA', '\x3', '\x2', '\x2', 
		'\x2', '\x33', '\xAC', '\x3', '\x2', '\x2', '\x2', '\x35', '\xAE', '\x3', 
		'\x2', '\x2', '\x2', '\x37', '\xB0', '\x3', '\x2', '\x2', '\x2', '\x39', 
		'\xB2', '\x3', '\x2', '\x2', '\x2', ';', '\xB4', '\x3', '\x2', '\x2', 
		'\x2', '=', '\xB7', '\x3', '\x2', '\x2', '\x2', '?', '@', '\a', 'o', '\x2', 
		'\x2', '@', '\x41', '\a', 'q', '\x2', '\x2', '\x41', '\x42', '\a', '\x66', 
		'\x2', '\x2', '\x42', '\x43', '\a', 'w', '\x2', '\x2', '\x43', '\x44', 
		'\a', 'n', '\x2', '\x2', '\x44', '\x45', '\a', 'g', '\x2', '\x2', '\x45', 
		'\x4', '\x3', '\x2', '\x2', '\x2', '\x46', 'G', '\a', 'k', '\x2', '\x2', 
		'G', 'H', '\a', 'o', '\x2', '\x2', 'H', 'I', '\a', 'r', '\x2', '\x2', 
		'I', 'J', '\a', 'q', '\x2', '\x2', 'J', 'K', '\a', 't', '\x2', '\x2', 
		'K', 'L', '\a', 'v', '\x2', '\x2', 'L', '\x6', '\x3', '\x2', '\x2', '\x2', 
		'M', 'N', '\a', 'k', '\x2', '\x2', 'N', 'O', '\a', 'p', '\x2', '\x2', 
		'O', 'P', '\a', '\x65', '\x2', '\x2', 'P', 'Q', '\a', 'n', '\x2', '\x2', 
		'Q', 'R', '\a', 'w', '\x2', '\x2', 'R', 'S', '\a', '\x66', '\x2', '\x2', 
		'S', 'T', '\a', 'g', '\x2', '\x2', 'T', '\b', '\x3', '\x2', '\x2', '\x2', 
		'U', 'V', '\a', 'g', '\x2', '\x2', 'V', 'W', '\a', 'z', '\x2', '\x2', 
		'W', 'X', '\a', 'v', '\x2', '\x2', 'X', 'Y', '\a', 'g', '\x2', '\x2', 
		'Y', 'Z', '\a', 't', '\x2', '\x2', 'Z', '[', '\a', 'p', '\x2', '\x2', 
		'[', '\\', '\a', '\x63', '\x2', '\x2', '\\', ']', '\a', 'n', '\x2', '\x2', 
		']', '\n', '\x3', '\x2', '\x2', '\x2', '^', '_', '\a', 'v', '\x2', '\x2', 
		'_', '`', '\a', '{', '\x2', '\x2', '`', '\x61', '\a', 'r', '\x2', '\x2', 
		'\x61', '\x62', '\a', 'g', '\x2', '\x2', '\x62', '\f', '\x3', '\x2', '\x2', 
		'\x2', '\x63', '\x64', '\a', 'N', '\x2', '\x2', '\x64', '\x65', '\a', 
		'k', '\x2', '\x2', '\x65', '\x66', '\a', 'u', '\x2', '\x2', '\x66', 'g', 
		'\a', 'v', '\x2', '\x2', 'g', '\xE', '\x3', '\x2', '\x2', '\x2', 'h', 
		'i', '\a', 'y', '\x2', '\x2', 'i', 'j', '\a', 'j', '\x2', '\x2', 'j', 
		'k', '\a', 'g', '\x2', '\x2', 'k', 'l', '\a', 't', '\x2', '\x2', 'l', 
		'm', '\a', 'g', '\x2', '\x2', 'm', '\x10', '\x3', '\x2', '\x2', '\x2', 
		'n', 'o', '\a', '\x61', '\x2', '\x2', 'o', '\x12', '\x3', '\x2', '\x2', 
		'\x2', 'p', 'q', '\a', 'p', '\x2', '\x2', 'q', 'r', '\a', 'k', '\x2', 
		'\x2', 'r', 's', '\a', 'n', '\x2', '\x2', 's', '\x14', '\x3', '\x2', '\x2', 
		'\x2', 't', 'v', '\t', '\x2', '\x2', '\x2', 'u', 't', '\x3', '\x2', '\x2', 
		'\x2', 'v', 'w', '\x3', '\x2', '\x2', '\x2', 'w', 'u', '\x3', '\x2', '\x2', 
		'\x2', 'w', 'x', '\x3', '\x2', '\x2', '\x2', 'x', 'y', '\x3', '\x2', '\x2', 
		'\x2', 'y', 'z', '\b', '\v', '\x2', '\x2', 'z', '\x16', '\x3', '\x2', 
		'\x2', '\x2', '{', '}', '\t', '\x3', '\x2', '\x2', '|', '{', '\x3', '\x2', 
		'\x2', '\x2', '}', '~', '\x3', '\x2', '\x2', '\x2', '~', '|', '\x3', '\x2', 
		'\x2', '\x2', '~', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x18', 
		'\x3', '\x2', '\x2', '\x2', '\x80', '\x84', '\t', '\x4', '\x2', '\x2', 
		'\x81', '\x83', '\t', '\x5', '\x2', '\x2', '\x82', '\x81', '\x3', '\x2', 
		'\x2', '\x2', '\x83', '\x86', '\x3', '\x2', '\x2', '\x2', '\x84', '\x82', 
		'\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\x3', '\x2', '\x2', '\x2', 
		'\x85', '\x1A', '\x3', '\x2', '\x2', '\x2', '\x86', '\x84', '\x3', '\x2', 
		'\x2', '\x2', '\x87', '\x88', '\x5', '\x1D', '\xF', '\x2', '\x88', '\x89', 
		'\a', '$', '\x2', '\x2', '\x89', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x93', '\a', '$', '\x2', '\x2', '\x8B', '\x92', '\n', '\x6', '\x2', '\x2', 
		'\x8C', '\x8F', '\a', '^', '\x2', '\x2', '\x8D', '\x90', '\v', '\x2', 
		'\x2', '\x2', '\x8E', '\x90', '\a', '\x2', '\x2', '\x3', '\x8F', '\x8D', 
		'\x3', '\x2', '\x2', '\x2', '\x8F', '\x8E', '\x3', '\x2', '\x2', '\x2', 
		'\x90', '\x92', '\x3', '\x2', '\x2', '\x2', '\x91', '\x8B', '\x3', '\x2', 
		'\x2', '\x2', '\x91', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x92', '\x95', 
		'\x3', '\x2', '\x2', '\x2', '\x93', '\x91', '\x3', '\x2', '\x2', '\x2', 
		'\x93', '\x94', '\x3', '\x2', '\x2', '\x2', '\x94', '\x1E', '\x3', '\x2', 
		'\x2', '\x2', '\x95', '\x93', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', 
		'\a', '-', '\x2', '\x2', '\x97', ' ', '\x3', '\x2', '\x2', '\x2', '\x98', 
		'\x99', '\a', '/', '\x2', '\x2', '\x99', '\"', '\x3', '\x2', '\x2', '\x2', 
		'\x9A', '\x9B', '\a', ',', '\x2', '\x2', '\x9B', '$', '\x3', '\x2', '\x2', 
		'\x2', '\x9C', '\x9D', '\a', '*', '\x2', '\x2', '\x9D', '&', '\x3', '\x2', 
		'\x2', '\x2', '\x9E', '\x9F', '\a', '+', '\x2', '\x2', '\x9F', '(', '\x3', 
		'\x2', '\x2', '\x2', '\xA0', '\xA1', '\a', '?', '\x2', '\x2', '\xA1', 
		'*', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\a', '<', '\x2', '\x2', 
		'\xA3', '\xA4', '\a', '<', '\x2', '\x2', '\xA4', ',', '\x3', '\x2', '\x2', 
		'\x2', '\xA5', '\xA6', '\a', '/', '\x2', '\x2', '\xA6', '\xA7', '\a', 
		'@', '\x2', '\x2', '\xA7', '.', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', 
		'\a', '(', '\x2', '\x2', '\xA9', '\x30', '\x3', '\x2', '\x2', '\x2', '\xAA', 
		'\xAB', '\a', '~', '\x2', '\x2', '\xAB', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\xAC', '\xAD', '\a', ']', '\x2', '\x2', '\xAD', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\xAE', '\xAF', '\a', '_', '\x2', '\x2', '\xAF', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB1', '\a', '.', '\x2', 
		'\x2', '\xB1', '\x38', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB3', '\a', 
		'<', '\x2', '\x2', '\xB3', ':', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB5', 
		'\a', '\x30', '\x2', '\x2', '\xB5', '<', '\x3', '\x2', '\x2', '\x2', '\xB6', 
		'\xB8', '\a', '\f', '\x2', '\x2', '\xB7', '\xB6', '\x3', '\x2', '\x2', 
		'\x2', '\xB8', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xB7', '\x3', 
		'\x2', '\x2', '\x2', '\xB9', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xBA', 
		'>', '\x3', '\x2', '\x2', '\x2', '\n', '\x2', 'w', '~', '\x84', '\x8F', 
		'\x91', '\x93', '\xB9', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
