//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from functional.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class functionalParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		WS=10, INT=11, ID=12, STR=13, UNTERMINATEDSTR=14, PLUS=15, MINUS=16, TIMES=17, 
		LPAREN=18, RPAREN=19, EQUALS=20, DBLCOLON=21, ARROW=22, AND=23, OR=24, 
		LBRACK=25, RBRACK=26, COMMA=27, JOIN=28, DOT=29, NL=30;
	public const int
		RULE_program = 0, RULE_definition = 1, RULE_predicate = 2, RULE_anontypename = 3, 
		RULE_simpleanontypename = 4, RULE_definitiontypename = 5, RULE_definitionsimpletypename = 6, 
		RULE_stmt = 7, RULE_whereclause = 8, RULE_patt = 9, RULE_bindpatt = 10, 
		RULE_expr = 11, RULE_mathexpr = 12, RULE_term = 13, RULE_call = 14, RULE_atom = 15;
	public static readonly string[] ruleNames = {
		"program", "definition", "predicate", "anontypename", "simpleanontypename", 
		"definitiontypename", "definitionsimpletypename", "stmt", "whereclause", 
		"patt", "bindpatt", "expr", "mathexpr", "term", "call", "atom"
	};

	private static readonly string[] _LiteralNames = {
		null, "'module'", "'import'", "'include'", "'external'", "'type'", "'List'", 
		"'where'", "'_'", "'nil'", null, null, null, null, null, "'+'", "'-'", 
		"'*'", "'('", "')'", "'='", "'::'", "'->'", "'&'", "'|'", "'['", "']'", 
		"','", "':'", "'.'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, "WS", "INT", 
		"ID", "STR", "UNTERMINATEDSTR", "PLUS", "MINUS", "TIMES", "LPAREN", "RPAREN", 
		"EQUALS", "DBLCOLON", "ARROW", "AND", "OR", "LBRACK", "RBRACK", "COMMA", 
		"JOIN", "DOT", "NL"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "functional.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static functionalParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public functionalParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public functionalParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		public ITerminalNode Eof() { return GetToken(functionalParser.Eof, 0); }
		public ITerminalNode NL() { return GetToken(functionalParser.NL, 0); }
		public DefinitionContext[] definition() {
			return GetRuleContexts<DefinitionContext>();
		}
		public DefinitionContext definition(int i) {
			return GetRuleContext<DefinitionContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 33;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==NL) {
				{
				State = 32; Match(NL);
				}
			}

			State = 38;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__1) | (1L << T__2) | (1L << T__3) | (1L << T__4) | (1L << ID))) != 0)) {
				{
				{
				State = 35; definition();
				}
				}
				State = 40;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 41; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DefinitionContext : ParserRuleContext {
		public DefinitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_definition; } }
	 
		public DefinitionContext() { }
		public virtual void CopyFrom(DefinitionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ModuleDefinitionContext : DefinitionContext {
		public ITerminalNode[] ID() { return GetTokens(functionalParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(functionalParser.ID, i);
		}
		public ITerminalNode NL() { return GetToken(functionalParser.NL, 0); }
		public ITerminalNode[] DOT() { return GetTokens(functionalParser.DOT); }
		public ITerminalNode DOT(int i) {
			return GetToken(functionalParser.DOT, i);
		}
		public ModuleDefinitionContext(DefinitionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitModuleDefinition(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionDefinitionContext : DefinitionContext {
		public PredicateContext predicate() {
			return GetRuleContext<PredicateContext>(0);
		}
		public ITerminalNode[] NL() { return GetTokens(functionalParser.NL); }
		public ITerminalNode NL(int i) {
			return GetToken(functionalParser.NL, i);
		}
		public StmtContext[] stmt() {
			return GetRuleContexts<StmtContext>();
		}
		public StmtContext stmt(int i) {
			return GetRuleContext<StmtContext>(i);
		}
		public FunctionDefinitionContext(DefinitionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionDefinition(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ImportDefinitionContext : DefinitionContext {
		public ITerminalNode[] ID() { return GetTokens(functionalParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(functionalParser.ID, i);
		}
		public ITerminalNode NL() { return GetToken(functionalParser.NL, 0); }
		public ITerminalNode[] DOT() { return GetTokens(functionalParser.DOT); }
		public ITerminalNode DOT(int i) {
			return GetToken(functionalParser.DOT, i);
		}
		public ImportDefinitionContext(DefinitionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitImportDefinition(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IncludeDefinitionContext : DefinitionContext {
		public ITerminalNode STR() { return GetToken(functionalParser.STR, 0); }
		public ITerminalNode NL() { return GetToken(functionalParser.NL, 0); }
		public IncludeDefinitionContext(DefinitionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIncludeDefinition(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ExternalFunctionDefinitionContext : DefinitionContext {
		public PredicateContext predicate() {
			return GetRuleContext<PredicateContext>(0);
		}
		public ITerminalNode NL() { return GetToken(functionalParser.NL, 0); }
		public ExternalFunctionDefinitionContext(DefinitionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExternalFunctionDefinition(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class TypeDefinitionContext : DefinitionContext {
		public ITerminalNode ID() { return GetToken(functionalParser.ID, 0); }
		public ITerminalNode EQUALS() { return GetToken(functionalParser.EQUALS, 0); }
		public DefinitiontypenameContext definitiontypename() {
			return GetRuleContext<DefinitiontypenameContext>(0);
		}
		public ITerminalNode NL() { return GetToken(functionalParser.NL, 0); }
		public TypeDefinitionContext(DefinitionContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeDefinition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DefinitionContext definition() {
		DefinitionContext _localctx = new DefinitionContext(Context, State);
		EnterRule(_localctx, 2, RULE_definition);
		int _la;
		try {
			int _alt;
			State = 90;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__0:
				_localctx = new ModuleDefinitionContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 43; Match(T__0);
				State = 48;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 44; Match(ID);
						State = 45; Match(DOT);
						}
						} 
					}
					State = 50;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
				}
				State = 51; Match(ID);
				State = 52; Match(NL);
				}
				break;
			case T__1:
				_localctx = new ImportDefinitionContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 53; Match(T__1);
				State = 58;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 54; Match(ID);
						State = 55; Match(DOT);
						}
						} 
					}
					State = 60;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
				}
				State = 61; Match(ID);
				State = 62; Match(NL);
				}
				break;
			case T__2:
				_localctx = new IncludeDefinitionContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 63; Match(T__2);
				State = 64; Match(STR);
				State = 65; Match(NL);
				}
				break;
			case T__3:
				_localctx = new ExternalFunctionDefinitionContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 66; Match(T__3);
				State = 67; predicate();
				State = 68; Match(NL);
				}
				break;
			case ID:
				_localctx = new FunctionDefinitionContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 70; predicate();
				State = 71; Match(NL);
				State = 77;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 72; stmt();
						State = 73; Match(NL);
						}
						} 
					}
					State = 79;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
				}
				State = 80; stmt();
				State = 82;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==NL) {
					{
					State = 81; Match(NL);
					}
				}

				}
				break;
			case T__4:
				_localctx = new TypeDefinitionContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 84; Match(T__4);
				State = 85; Match(ID);
				State = 86; Match(EQUALS);
				State = 87; definitiontypename();
				State = 88; Match(NL);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PredicateContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(functionalParser.ID, 0); }
		public ITerminalNode DBLCOLON() { return GetToken(functionalParser.DBLCOLON, 0); }
		public AnontypenameContext anontypename() {
			return GetRuleContext<AnontypenameContext>(0);
		}
		public PredicateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_predicate; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPredicate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PredicateContext predicate() {
		PredicateContext _localctx = new PredicateContext(Context, State);
		EnterRule(_localctx, 4, RULE_predicate);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 92; Match(ID);
			State = 93; Match(DBLCOLON);
			State = 94; anontypename();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AnontypenameContext : ParserRuleContext {
		public AnontypenameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_anontypename; } }
	 
		public AnontypenameContext() { }
		public virtual void CopyFrom(AnontypenameContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class CompositeAnontypenameContext : AnontypenameContext {
		public SimpleanontypenameContext[] simpleanontypename() {
			return GetRuleContexts<SimpleanontypenameContext>();
		}
		public SimpleanontypenameContext simpleanontypename(int i) {
			return GetRuleContext<SimpleanontypenameContext>(i);
		}
		public ITerminalNode[] ARROW() { return GetTokens(functionalParser.ARROW); }
		public ITerminalNode ARROW(int i) {
			return GetToken(functionalParser.ARROW, i);
		}
		public CompositeAnontypenameContext(AnontypenameContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCompositeAnontypename(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SimpleanontypenameAnontypenameContext : AnontypenameContext {
		public SimpleanontypenameContext simpleanontypename() {
			return GetRuleContext<SimpleanontypenameContext>(0);
		}
		public SimpleanontypenameAnontypenameContext(AnontypenameContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSimpleanontypenameAnontypename(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AnontypenameContext anontypename() {
		AnontypenameContext _localctx = new AnontypenameContext(Context, State);
		EnterRule(_localctx, 6, RULE_anontypename);
		try {
			int _alt;
			State = 106;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				_localctx = new CompositeAnontypenameContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 99;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 96; simpleanontypename();
						State = 97; Match(ARROW);
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 101;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				State = 103; simpleanontypename();
				}
				break;
			case 2:
				_localctx = new SimpleanontypenameAnontypenameContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 105; simpleanontypename();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SimpleanontypenameContext : ParserRuleContext {
		public SimpleanontypenameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_simpleanontypename; } }
	 
		public SimpleanontypenameContext() { }
		public virtual void CopyFrom(SimpleanontypenameContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class AnontypenameSimpleanontypenameContext : SimpleanontypenameContext {
		public ITerminalNode LPAREN() { return GetToken(functionalParser.LPAREN, 0); }
		public AnontypenameContext anontypename() {
			return GetRuleContext<AnontypenameContext>(0);
		}
		public ITerminalNode RPAREN() { return GetToken(functionalParser.RPAREN, 0); }
		public AnontypenameSimpleanontypenameContext(SimpleanontypenameContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAnontypenameSimpleanontypename(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NamedSimpleanontypenameContext : SimpleanontypenameContext {
		public ITerminalNode ID() { return GetToken(functionalParser.ID, 0); }
		public NamedSimpleanontypenameContext(SimpleanontypenameContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNamedSimpleanontypename(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ListSimpleanontypenameContext : SimpleanontypenameContext {
		public SimpleanontypenameContext simpleanontypename() {
			return GetRuleContext<SimpleanontypenameContext>(0);
		}
		public ListSimpleanontypenameContext(SimpleanontypenameContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitListSimpleanontypename(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SimpleanontypenameContext simpleanontypename() {
		SimpleanontypenameContext _localctx = new SimpleanontypenameContext(Context, State);
		EnterRule(_localctx, 8, RULE_simpleanontypename);
		try {
			State = 115;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__5:
				_localctx = new ListSimpleanontypenameContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 108; Match(T__5);
				State = 109; simpleanontypename();
				}
				break;
			case ID:
				_localctx = new NamedSimpleanontypenameContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 110; Match(ID);
				}
				break;
			case LPAREN:
				_localctx = new AnontypenameSimpleanontypenameContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 111; Match(LPAREN);
				State = 112; anontypename();
				State = 113; Match(RPAREN);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DefinitiontypenameContext : ParserRuleContext {
		public DefinitiontypenameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_definitiontypename; } }
	 
		public DefinitiontypenameContext() { }
		public virtual void CopyFrom(DefinitiontypenameContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class AndtypeDefinitiontypenameContext : DefinitiontypenameContext {
		public ITerminalNode LPAREN() { return GetToken(functionalParser.LPAREN, 0); }
		public DefinitionsimpletypenameContext[] definitionsimpletypename() {
			return GetRuleContexts<DefinitionsimpletypenameContext>();
		}
		public DefinitionsimpletypenameContext definitionsimpletypename(int i) {
			return GetRuleContext<DefinitionsimpletypenameContext>(i);
		}
		public ITerminalNode RPAREN() { return GetToken(functionalParser.RPAREN, 0); }
		public ITerminalNode[] AND() { return GetTokens(functionalParser.AND); }
		public ITerminalNode AND(int i) {
			return GetToken(functionalParser.AND, i);
		}
		public AndtypeDefinitiontypenameContext(DefinitiontypenameContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAndtypeDefinitiontypename(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class OrtypeDefinitiontypenameContext : DefinitiontypenameContext {
		public ITerminalNode LPAREN() { return GetToken(functionalParser.LPAREN, 0); }
		public ITerminalNode[] ID() { return GetTokens(functionalParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(functionalParser.ID, i);
		}
		public DefinitionsimpletypenameContext[] definitionsimpletypename() {
			return GetRuleContexts<DefinitionsimpletypenameContext>();
		}
		public DefinitionsimpletypenameContext definitionsimpletypename(int i) {
			return GetRuleContext<DefinitionsimpletypenameContext>(i);
		}
		public ITerminalNode RPAREN() { return GetToken(functionalParser.RPAREN, 0); }
		public ITerminalNode[] OR() { return GetTokens(functionalParser.OR); }
		public ITerminalNode OR(int i) {
			return GetToken(functionalParser.OR, i);
		}
		public OrtypeDefinitiontypenameContext(DefinitiontypenameContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOrtypeDefinitiontypename(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DefinitiontypenameContext definitiontypename() {
		DefinitiontypenameContext _localctx = new DefinitiontypenameContext(Context, State);
		EnterRule(_localctx, 10, RULE_definitiontypename);
		try {
			int _alt;
			State = 141;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
			case 1:
				_localctx = new AndtypeDefinitiontypenameContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 117; Match(LPAREN);
				State = 121;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 118; definitionsimpletypename();
						State = 119; Match(AND);
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 123;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,10,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				State = 125; definitionsimpletypename();
				State = 126; Match(RPAREN);
				}
				break;
			case 2:
				_localctx = new OrtypeDefinitiontypenameContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 128; Match(LPAREN);
				State = 133;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 129; Match(ID);
						State = 130; definitionsimpletypename();
						State = 131; Match(OR);
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 135;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				State = 137; Match(ID);
				State = 138; definitionsimpletypename();
				State = 139; Match(RPAREN);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DefinitionsimpletypenameContext : ParserRuleContext {
		public DefinitionsimpletypenameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_definitionsimpletypename; } }
	 
		public DefinitionsimpletypenameContext() { }
		public virtual void CopyFrom(DefinitionsimpletypenameContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ListDefinitionsimpletypenameContext : DefinitionsimpletypenameContext {
		public DefinitionsimpletypenameContext definitionsimpletypename() {
			return GetRuleContext<DefinitionsimpletypenameContext>(0);
		}
		public ListDefinitionsimpletypenameContext(DefinitionsimpletypenameContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitListDefinitionsimpletypename(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NamedDefinitionsimpletypenameContext : DefinitionsimpletypenameContext {
		public ITerminalNode ID() { return GetToken(functionalParser.ID, 0); }
		public NamedDefinitionsimpletypenameContext(DefinitionsimpletypenameContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNamedDefinitionsimpletypename(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DefinitionsimpletypenameContext definitionsimpletypename() {
		DefinitionsimpletypenameContext _localctx = new DefinitionsimpletypenameContext(Context, State);
		EnterRule(_localctx, 12, RULE_definitionsimpletypename);
		try {
			State = 146;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__5:
				_localctx = new ListDefinitionsimpletypenameContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 143; Match(T__5);
				State = 144; definitionsimpletypename();
				}
				break;
			case ID:
				_localctx = new NamedDefinitionsimpletypenameContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 145; Match(ID);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StmtContext : ParserRuleContext {
		public StmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmt; } }
	 
		public StmtContext() { }
		public virtual void CopyFrom(StmtContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class FuncDefStmtContext : StmtContext {
		public ITerminalNode ID() { return GetToken(functionalParser.ID, 0); }
		public ITerminalNode EQUALS() { return GetToken(functionalParser.EQUALS, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public WhereclauseContext whereclause() {
			return GetRuleContext<WhereclauseContext>(0);
		}
		public PattContext[] patt() {
			return GetRuleContexts<PattContext>();
		}
		public PattContext patt(int i) {
			return GetRuleContext<PattContext>(i);
		}
		public ITerminalNode NL() { return GetToken(functionalParser.NL, 0); }
		public FuncDefStmtContext(StmtContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFuncDefStmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StmtContext stmt() {
		StmtContext _localctx = new StmtContext(Context, State);
		EnterRule(_localctx, 14, RULE_stmt);
		int _la;
		try {
			_localctx = new FuncDefStmtContext(_localctx);
			EnterOuterAlt(_localctx, 1);
			{
			State = 148; Match(ID);
			State = 152;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__7) | (1L << INT) | (1L << ID) | (1L << LPAREN) | (1L << LBRACK))) != 0)) {
				{
				{
				State = 149; patt();
				}
				}
				State = 154;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 155; Match(EQUALS);
			State = 156; expr();
			State = 158;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
			case 1:
				{
				State = 157; Match(NL);
				}
				break;
			}
			State = 160; whereclause();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class WhereclauseContext : ParserRuleContext {
		public WhereclauseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_whereclause; } }
	 
		public WhereclauseContext() { }
		public virtual void CopyFrom(WhereclauseContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class NoWhereClauseContext : WhereclauseContext {
		public NoWhereClauseContext(WhereclauseContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNoWhereClause(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class WhereClauseContext : WhereclauseContext {
		public BindpattContext[] bindpatt() {
			return GetRuleContexts<BindpattContext>();
		}
		public BindpattContext bindpatt(int i) {
			return GetRuleContext<BindpattContext>(i);
		}
		public ITerminalNode[] EQUALS() { return GetTokens(functionalParser.EQUALS); }
		public ITerminalNode EQUALS(int i) {
			return GetToken(functionalParser.EQUALS, i);
		}
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode[] NL() { return GetTokens(functionalParser.NL); }
		public ITerminalNode NL(int i) {
			return GetToken(functionalParser.NL, i);
		}
		public WhereClauseContext(WhereclauseContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhereClause(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public WhereclauseContext whereclause() {
		WhereclauseContext _localctx = new WhereclauseContext(Context, State);
		EnterRule(_localctx, 16, RULE_whereclause);
		try {
			int _alt;
			State = 173;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__6:
				_localctx = new WhereClauseContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 162; Match(T__6);
				State = 168;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 163; bindpatt();
						State = 164; Match(EQUALS);
						State = 165; expr();
						State = 166; Match(NL);
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 170;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,16,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				}
				break;
			case Eof:
			case T__0:
			case T__1:
			case T__2:
			case T__3:
			case T__4:
			case ID:
			case NL:
				_localctx = new NoWhereClauseContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PattContext : ParserRuleContext {
		public PattContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_patt; } }
	 
		public PattContext() { }
		public virtual void CopyFrom(PattContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ConstIntPatternContext : PattContext {
		public ITerminalNode INT() { return GetToken(functionalParser.INT, 0); }
		public ConstIntPatternContext(PattContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConstIntPattern(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EmptyListPatternContext : PattContext {
		public ITerminalNode LBRACK() { return GetToken(functionalParser.LBRACK, 0); }
		public ITerminalNode RBRACK() { return GetToken(functionalParser.RBRACK, 0); }
		public EmptyListPatternContext(PattContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEmptyListPattern(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AndTypePatternContext : PattContext {
		public ITerminalNode LPAREN() { return GetToken(functionalParser.LPAREN, 0); }
		public PattContext[] patt() {
			return GetRuleContexts<PattContext>();
		}
		public PattContext patt(int i) {
			return GetRuleContext<PattContext>(i);
		}
		public ITerminalNode RPAREN() { return GetToken(functionalParser.RPAREN, 0); }
		public ITerminalNode[] AND() { return GetTokens(functionalParser.AND); }
		public ITerminalNode AND(int i) {
			return GetToken(functionalParser.AND, i);
		}
		public AndTypePatternContext(PattContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAndTypePattern(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BindPatternContext : PattContext {
		public ITerminalNode ID() { return GetToken(functionalParser.ID, 0); }
		public BindPatternContext(PattContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBindPattern(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class OrTypePatternContext : PattContext {
		public ITerminalNode LPAREN() { return GetToken(functionalParser.LPAREN, 0); }
		public ITerminalNode ID() { return GetToken(functionalParser.ID, 0); }
		public PattContext patt() {
			return GetRuleContext<PattContext>(0);
		}
		public ITerminalNode RPAREN() { return GetToken(functionalParser.RPAREN, 0); }
		public OrTypePatternContext(PattContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOrTypePattern(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DiscardPatternContext : PattContext {
		public DiscardPatternContext(PattContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDiscardPattern(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ListPatternContext : PattContext {
		public ITerminalNode LPAREN() { return GetToken(functionalParser.LPAREN, 0); }
		public PattContext[] patt() {
			return GetRuleContexts<PattContext>();
		}
		public PattContext patt(int i) {
			return GetRuleContext<PattContext>(i);
		}
		public ITerminalNode RPAREN() { return GetToken(functionalParser.RPAREN, 0); }
		public ITerminalNode[] JOIN() { return GetTokens(functionalParser.JOIN); }
		public ITerminalNode JOIN(int i) {
			return GetToken(functionalParser.JOIN, i);
		}
		public ListPatternContext(PattContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitListPattern(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PattContext patt() {
		PattContext _localctx = new PattContext(Context, State);
		EnterRule(_localctx, 18, RULE_patt);
		try {
			int _alt;
			State = 207;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,20,Context) ) {
			case 1:
				_localctx = new BindPatternContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 175; Match(ID);
				}
				break;
			case 2:
				_localctx = new DiscardPatternContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 176; Match(T__7);
				}
				break;
			case 3:
				_localctx = new AndTypePatternContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 177; Match(LPAREN);
				State = 181;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 178; patt();
						State = 179; Match(AND);
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 183;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,18,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				State = 185; patt();
				State = 186; Match(RPAREN);
				}
				break;
			case 4:
				_localctx = new OrTypePatternContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 188; Match(LPAREN);
				State = 189; Match(ID);
				State = 190; patt();
				State = 191; Match(RPAREN);
				}
				break;
			case 5:
				_localctx = new EmptyListPatternContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 193; Match(LBRACK);
				State = 194; Match(RBRACK);
				}
				break;
			case 6:
				_localctx = new ListPatternContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 195; Match(LPAREN);
				State = 199;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 196; patt();
						State = 197; Match(JOIN);
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 201;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,19,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				State = 203; patt();
				State = 204; Match(RPAREN);
				}
				break;
			case 7:
				_localctx = new ConstIntPatternContext(_localctx);
				EnterOuterAlt(_localctx, 7);
				{
				State = 206; Match(INT);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BindpattContext : ParserRuleContext {
		public BindpattContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_bindpatt; } }
	 
		public BindpattContext() { }
		public virtual void CopyFrom(BindpattContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class AndTypeBindPatternContext : BindpattContext {
		public ITerminalNode LPAREN() { return GetToken(functionalParser.LPAREN, 0); }
		public BindpattContext[] bindpatt() {
			return GetRuleContexts<BindpattContext>();
		}
		public BindpattContext bindpatt(int i) {
			return GetRuleContext<BindpattContext>(i);
		}
		public ITerminalNode RPAREN() { return GetToken(functionalParser.RPAREN, 0); }
		public ITerminalNode[] AND() { return GetTokens(functionalParser.AND); }
		public ITerminalNode AND(int i) {
			return GetToken(functionalParser.AND, i);
		}
		public AndTypeBindPatternContext(BindpattContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAndTypeBindPattern(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DiscardBindPatternContext : BindpattContext {
		public DiscardBindPatternContext(BindpattContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDiscardBindPattern(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class OrTypeBindPatternContext : BindpattContext {
		public ITerminalNode LPAREN() { return GetToken(functionalParser.LPAREN, 0); }
		public ITerminalNode ID() { return GetToken(functionalParser.ID, 0); }
		public BindpattContext bindpatt() {
			return GetRuleContext<BindpattContext>(0);
		}
		public ITerminalNode RPAREN() { return GetToken(functionalParser.RPAREN, 0); }
		public OrTypeBindPatternContext(BindpattContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOrTypeBindPattern(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class BindBindPatternContext : BindpattContext {
		public ITerminalNode ID() { return GetToken(functionalParser.ID, 0); }
		public BindBindPatternContext(BindpattContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBindBindPattern(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ListBindPatternContext : BindpattContext {
		public ITerminalNode LPAREN() { return GetToken(functionalParser.LPAREN, 0); }
		public BindpattContext[] bindpatt() {
			return GetRuleContexts<BindpattContext>();
		}
		public BindpattContext bindpatt(int i) {
			return GetRuleContext<BindpattContext>(i);
		}
		public ITerminalNode RPAREN() { return GetToken(functionalParser.RPAREN, 0); }
		public ITerminalNode[] JOIN() { return GetTokens(functionalParser.JOIN); }
		public ITerminalNode JOIN(int i) {
			return GetToken(functionalParser.JOIN, i);
		}
		public ListBindPatternContext(BindpattContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitListBindPattern(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BindpattContext bindpatt() {
		BindpattContext _localctx = new BindpattContext(Context, State);
		EnterRule(_localctx, 20, RULE_bindpatt);
		try {
			int _alt;
			State = 238;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,23,Context) ) {
			case 1:
				_localctx = new BindBindPatternContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 209; Match(ID);
				}
				break;
			case 2:
				_localctx = new DiscardBindPatternContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 210; Match(T__7);
				}
				break;
			case 3:
				_localctx = new AndTypeBindPatternContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 211; Match(LPAREN);
				State = 215;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 212; bindpatt();
						State = 213; Match(AND);
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 217;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,21,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				State = 219; bindpatt();
				State = 220; Match(RPAREN);
				}
				break;
			case 4:
				_localctx = new OrTypeBindPatternContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 222; Match(LPAREN);
				State = 223; Match(ID);
				State = 224; bindpatt();
				State = 225; Match(RPAREN);
				}
				break;
			case 5:
				_localctx = new ListBindPatternContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 227; Match(LPAREN);
				State = 231;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 228; bindpatt();
						State = 229; Match(JOIN);
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 233;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,22,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				State = 235; bindpatt();
				State = 236; Match(RPAREN);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class MathexprExprContext : ExprContext {
		public MathexprContext mathexpr() {
			return GetRuleContext<MathexprContext>(0);
		}
		public MathexprExprContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMathexprExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class JoinExprContext : ExprContext {
		public MathexprContext mathexpr() {
			return GetRuleContext<MathexprContext>(0);
		}
		public ITerminalNode JOIN() { return GetToken(functionalParser.JOIN, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public JoinExprContext(ExprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJoinExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		ExprContext _localctx = new ExprContext(Context, State);
		EnterRule(_localctx, 22, RULE_expr);
		try {
			State = 245;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,24,Context) ) {
			case 1:
				_localctx = new JoinExprContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 240; mathexpr(0);
				State = 241; Match(JOIN);
				State = 242; expr();
				}
				break;
			case 2:
				_localctx = new MathexprExprContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 244; mathexpr(0);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MathexprContext : ParserRuleContext {
		public MathexprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mathexpr; } }
	 
		public MathexprContext() { }
		public virtual void CopyFrom(MathexprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class MinusMathexprContext : MathexprContext {
		public MathexprContext mathexpr() {
			return GetRuleContext<MathexprContext>(0);
		}
		public ITerminalNode MINUS() { return GetToken(functionalParser.MINUS, 0); }
		public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		public MinusMathexprContext(MathexprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMinusMathexpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class TermMathexprContext : MathexprContext {
		public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		public TermMathexprContext(MathexprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTermMathexpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PlusMathexprContext : MathexprContext {
		public MathexprContext mathexpr() {
			return GetRuleContext<MathexprContext>(0);
		}
		public ITerminalNode PLUS() { return GetToken(functionalParser.PLUS, 0); }
		public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		public PlusMathexprContext(MathexprContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPlusMathexpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MathexprContext mathexpr() {
		return mathexpr(0);
	}

	private MathexprContext mathexpr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		MathexprContext _localctx = new MathexprContext(Context, _parentState);
		MathexprContext _prevctx = _localctx;
		int _startState = 24;
		EnterRecursionRule(_localctx, 24, RULE_mathexpr, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			_localctx = new TermMathexprContext(_localctx);
			Context = _localctx;
			_prevctx = _localctx;

			State = 248; term(0);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 258;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,26,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 256;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,25,Context) ) {
					case 1:
						{
						_localctx = new PlusMathexprContext(new MathexprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_mathexpr);
						State = 250;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 251; Match(PLUS);
						State = 252; term(0);
						}
						break;
					case 2:
						{
						_localctx = new MinusMathexprContext(new MathexprContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_mathexpr);
						State = 253;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 254; Match(MINUS);
						State = 255; term(0);
						}
						break;
					}
					} 
				}
				State = 260;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,26,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class TermContext : ParserRuleContext {
		public TermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_term; } }
	 
		public TermContext() { }
		public virtual void CopyFrom(TermContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class CallTermContext : TermContext {
		public CallContext call() {
			return GetRuleContext<CallContext>(0);
		}
		public CallTermContext(TermContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCallTerm(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class TimesTermContext : TermContext {
		public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		public ITerminalNode TIMES() { return GetToken(functionalParser.TIMES, 0); }
		public CallContext call() {
			return GetRuleContext<CallContext>(0);
		}
		public TimesTermContext(TermContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTimesTerm(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TermContext term() {
		return term(0);
	}

	private TermContext term(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		TermContext _localctx = new TermContext(Context, _parentState);
		TermContext _prevctx = _localctx;
		int _startState = 26;
		EnterRecursionRule(_localctx, 26, RULE_term, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			_localctx = new CallTermContext(_localctx);
			Context = _localctx;
			_prevctx = _localctx;

			State = 262; call();
			}
			Context.Stop = TokenStream.LT(-1);
			State = 269;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,27,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new TimesTermContext(new TermContext(_parentctx, _parentState));
					PushNewRecursionContext(_localctx, _startState, RULE_term);
					State = 264;
					if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
					State = 265; Match(TIMES);
					State = 266; call();
					}
					} 
				}
				State = 271;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,27,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class CallContext : ParserRuleContext {
		public CallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_call; } }
	 
		public CallContext() { }
		public virtual void CopyFrom(CallContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class CallCallContext : CallContext {
		public AtomContext[] atom() {
			return GetRuleContexts<AtomContext>();
		}
		public AtomContext atom(int i) {
			return GetRuleContext<AtomContext>(i);
		}
		public CallCallContext(CallContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCallCall(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AtomCallContext : CallContext {
		public AtomContext atom() {
			return GetRuleContext<AtomContext>(0);
		}
		public AtomCallContext(CallContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAtomCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CallContext call() {
		CallContext _localctx = new CallContext(Context, State);
		EnterRule(_localctx, 28, RULE_call);
		try {
			int _alt;
			State = 279;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,29,Context) ) {
			case 1:
				_localctx = new CallCallContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 272; atom();
				State = 274;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 273; atom();
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 276;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,28,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				}
				break;
			case 2:
				_localctx = new AtomCallContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 278; atom();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AtomContext : ParserRuleContext {
		public AtomContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_atom; } }
	 
		public AtomContext() { }
		public virtual void CopyFrom(AtomContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class StringAtomContext : AtomContext {
		public ITerminalNode STR() { return GetToken(functionalParser.STR, 0); }
		public StringAtomContext(AtomContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStringAtom(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NilAtomContext : AtomContext {
		public NilAtomContext(AtomContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNilAtom(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ListAtomContext : AtomContext {
		public ITerminalNode LBRACK() { return GetToken(functionalParser.LBRACK, 0); }
		public ITerminalNode RBRACK() { return GetToken(functionalParser.RBRACK, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(functionalParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(functionalParser.COMMA, i);
		}
		public ITerminalNode DBLCOLON() { return GetToken(functionalParser.DBLCOLON, 0); }
		public AnontypenameContext anontypename() {
			return GetRuleContext<AnontypenameContext>(0);
		}
		public ListAtomContext(AtomContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitListAtom(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ParenAtomContext : AtomContext {
		public ITerminalNode LPAREN() { return GetToken(functionalParser.LPAREN, 0); }
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode RPAREN() { return GetToken(functionalParser.RPAREN, 0); }
		public ParenAtomContext(AtomContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParenAtom(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class VarAtomContext : AtomContext {
		public ITerminalNode ID() { return GetToken(functionalParser.ID, 0); }
		public ITerminalNode DBLCOLON() { return GetToken(functionalParser.DBLCOLON, 0); }
		public AnontypenameContext anontypename() {
			return GetRuleContext<AnontypenameContext>(0);
		}
		public VarAtomContext(AtomContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVarAtom(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IntAtomContext : AtomContext {
		public ITerminalNode INT() { return GetToken(functionalParser.INT, 0); }
		public IntAtomContext(AtomContext context) { CopyFrom(context); }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IfunctionalVisitor<TResult> typedVisitor = visitor as IfunctionalVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIntAtom(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AtomContext atom() {
		AtomContext _localctx = new AtomContext(Context, State);
		EnterRule(_localctx, 30, RULE_atom);
		int _la;
		try {
			int _alt;
			State = 310;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case INT:
				_localctx = new IntAtomContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 281; Match(INT);
				}
				break;
			case ID:
				_localctx = new VarAtomContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 282; Match(ID);
				State = 285;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,30,Context) ) {
				case 1:
					{
					State = 283; Match(DBLCOLON);
					State = 284; anontypename();
					}
					break;
				}
				}
				break;
			case STR:
				_localctx = new StringAtomContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 287; Match(STR);
				}
				break;
			case T__8:
				_localctx = new NilAtomContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 288; Match(T__8);
				}
				break;
			case LPAREN:
				_localctx = new ParenAtomContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 289; Match(LPAREN);
				State = 290; expr();
				State = 291; Match(RPAREN);
				}
				break;
			case LBRACK:
				_localctx = new ListAtomContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 293; Match(LBRACK);
				State = 299;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,31,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 294; expr();
						State = 295; Match(COMMA);
						}
						} 
					}
					State = 301;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,31,Context);
				}
				State = 303;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__8) | (1L << INT) | (1L << ID) | (1L << STR) | (1L << LPAREN) | (1L << LBRACK))) != 0)) {
					{
					State = 302; expr();
					}
				}

				State = 305; Match(RBRACK);
				State = 308;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,33,Context) ) {
				case 1:
					{
					State = 306; Match(DBLCOLON);
					State = 307; anontypename();
					}
					break;
				}
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 12: return mathexpr_sempred((MathexprContext)_localctx, predIndex);
		case 13: return term_sempred((TermContext)_localctx, predIndex);
		}
		return true;
	}
	private bool mathexpr_sempred(MathexprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 3);
		case 1: return Precpred(Context, 2);
		}
		return true;
	}
	private bool term_sempred(TermContext _localctx, int predIndex) {
		switch (predIndex) {
		case 2: return Precpred(Context, 2);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', ' ', '\x13B', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x3', '\x2', '\x5', '\x2', '$', '\n', '\x2', '\x3', 
		'\x2', '\a', '\x2', '\'', '\n', '\x2', '\f', '\x2', '\xE', '\x2', '*', 
		'\v', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\a', '\x3', '\x31', '\n', '\x3', '\f', '\x3', '\xE', '\x3', '\x34', 
		'\v', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\a', '\x3', ';', '\n', '\x3', '\f', '\x3', '\xE', '\x3', '>', 
		'\v', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', 
		'N', '\n', '\x3', '\f', '\x3', '\xE', '\x3', 'Q', '\v', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x5', '\x3', 'U', '\n', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x5', 
		'\x3', ']', '\n', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x6', '\x5', '\x66', 
		'\n', '\x5', '\r', '\x5', '\xE', '\x5', 'g', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x5', '\x5', 'm', '\n', '\x5', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x5', '\x6', 'v', '\n', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x6', '\a', '|', '\n', '\a', '\r', '\a', '\xE', '\a', '}', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x6', '\a', '\x88', '\n', '\a', '\r', 
		'\a', '\xE', '\a', '\x89', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x5', '\a', '\x90', '\n', '\a', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x5', '\b', '\x95', '\n', '\b', '\x3', '\t', '\x3', '\t', '\a', 
		'\t', '\x99', '\n', '\t', '\f', '\t', '\xE', '\t', '\x9C', '\v', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x5', '\t', '\xA1', '\n', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x6', '\n', '\xAB', '\n', '\n', '\r', 
		'\n', '\xE', '\n', '\xAC', '\x3', '\n', '\x5', '\n', '\xB0', '\n', '\n', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x6', '\v', '\xB8', '\n', '\v', '\r', '\v', '\xE', '\v', '\xB9', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x6', '\v', '\xCA', '\n', '\v', 
		'\r', '\v', '\xE', '\v', '\xCB', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x5', '\v', '\xD2', '\n', '\v', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x6', '\f', '\xDA', 
		'\n', '\f', '\r', '\f', '\xE', '\f', '\xDB', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x6', '\f', 
		'\xEA', '\n', '\f', '\r', '\f', '\xE', '\f', '\xEB', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x5', '\f', '\xF1', '\n', '\f', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x5', '\r', '\xF8', '\n', 
		'\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\a', '\xE', '\x103', 
		'\n', '\xE', '\f', '\xE', '\xE', '\xE', '\x106', '\v', '\xE', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\a', '\xF', '\x10E', '\n', '\xF', '\f', '\xF', '\xE', '\xF', '\x111', 
		'\v', '\xF', '\x3', '\x10', '\x3', '\x10', '\x6', '\x10', '\x115', '\n', 
		'\x10', '\r', '\x10', '\xE', '\x10', '\x116', '\x3', '\x10', '\x5', '\x10', 
		'\x11A', '\n', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x5', '\x11', '\x120', '\n', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\a', '\x11', '\x12C', '\n', 
		'\x11', '\f', '\x11', '\xE', '\x11', '\x12F', '\v', '\x11', '\x3', '\x11', 
		'\x5', '\x11', '\x132', '\n', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x5', '\x11', '\x137', '\n', '\x11', '\x5', '\x11', '\x139', 
		'\n', '\x11', '\x3', '\x11', '\x2', '\x4', '\x1A', '\x1C', '\x12', '\x2', 
		'\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', 
		'\x18', '\x1A', '\x1C', '\x1E', ' ', '\x2', '\x2', '\x2', '\x15E', '\x2', 
		'#', '\x3', '\x2', '\x2', '\x2', '\x4', '\\', '\x3', '\x2', '\x2', '\x2', 
		'\x6', '^', '\x3', '\x2', '\x2', '\x2', '\b', 'l', '\x3', '\x2', '\x2', 
		'\x2', '\n', 'u', '\x3', '\x2', '\x2', '\x2', '\f', '\x8F', '\x3', '\x2', 
		'\x2', '\x2', '\xE', '\x94', '\x3', '\x2', '\x2', '\x2', '\x10', '\x96', 
		'\x3', '\x2', '\x2', '\x2', '\x12', '\xAF', '\x3', '\x2', '\x2', '\x2', 
		'\x14', '\xD1', '\x3', '\x2', '\x2', '\x2', '\x16', '\xF0', '\x3', '\x2', 
		'\x2', '\x2', '\x18', '\xF7', '\x3', '\x2', '\x2', '\x2', '\x1A', '\xF9', 
		'\x3', '\x2', '\x2', '\x2', '\x1C', '\x107', '\x3', '\x2', '\x2', '\x2', 
		'\x1E', '\x119', '\x3', '\x2', '\x2', '\x2', ' ', '\x138', '\x3', '\x2', 
		'\x2', '\x2', '\"', '$', '\a', ' ', '\x2', '\x2', '#', '\"', '\x3', '\x2', 
		'\x2', '\x2', '#', '$', '\x3', '\x2', '\x2', '\x2', '$', '(', '\x3', '\x2', 
		'\x2', '\x2', '%', '\'', '\x5', '\x4', '\x3', '\x2', '&', '%', '\x3', 
		'\x2', '\x2', '\x2', '\'', '*', '\x3', '\x2', '\x2', '\x2', '(', '&', 
		'\x3', '\x2', '\x2', '\x2', '(', ')', '\x3', '\x2', '\x2', '\x2', ')', 
		'+', '\x3', '\x2', '\x2', '\x2', '*', '(', '\x3', '\x2', '\x2', '\x2', 
		'+', ',', '\a', '\x2', '\x2', '\x3', ',', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '-', '\x32', '\a', '\x3', '\x2', '\x2', '.', '/', '\a', '\xE', 
		'\x2', '\x2', '/', '\x31', '\a', '\x1F', '\x2', '\x2', '\x30', '.', '\x3', 
		'\x2', '\x2', '\x2', '\x31', '\x34', '\x3', '\x2', '\x2', '\x2', '\x32', 
		'\x30', '\x3', '\x2', '\x2', '\x2', '\x32', '\x33', '\x3', '\x2', '\x2', 
		'\x2', '\x33', '\x35', '\x3', '\x2', '\x2', '\x2', '\x34', '\x32', '\x3', 
		'\x2', '\x2', '\x2', '\x35', '\x36', '\a', '\xE', '\x2', '\x2', '\x36', 
		']', '\a', ' ', '\x2', '\x2', '\x37', '<', '\a', '\x4', '\x2', '\x2', 
		'\x38', '\x39', '\a', '\xE', '\x2', '\x2', '\x39', ';', '\a', '\x1F', 
		'\x2', '\x2', ':', '\x38', '\x3', '\x2', '\x2', '\x2', ';', '>', '\x3', 
		'\x2', '\x2', '\x2', '<', ':', '\x3', '\x2', '\x2', '\x2', '<', '=', '\x3', 
		'\x2', '\x2', '\x2', '=', '?', '\x3', '\x2', '\x2', '\x2', '>', '<', '\x3', 
		'\x2', '\x2', '\x2', '?', '@', '\a', '\xE', '\x2', '\x2', '@', ']', '\a', 
		' ', '\x2', '\x2', '\x41', '\x42', '\a', '\x5', '\x2', '\x2', '\x42', 
		'\x43', '\a', '\xF', '\x2', '\x2', '\x43', ']', '\a', ' ', '\x2', '\x2', 
		'\x44', '\x45', '\a', '\x6', '\x2', '\x2', '\x45', '\x46', '\x5', '\x6', 
		'\x4', '\x2', '\x46', 'G', '\a', ' ', '\x2', '\x2', 'G', ']', '\x3', '\x2', 
		'\x2', '\x2', 'H', 'I', '\x5', '\x6', '\x4', '\x2', 'I', 'O', '\a', ' ', 
		'\x2', '\x2', 'J', 'K', '\x5', '\x10', '\t', '\x2', 'K', 'L', '\a', ' ', 
		'\x2', '\x2', 'L', 'N', '\x3', '\x2', '\x2', '\x2', 'M', 'J', '\x3', '\x2', 
		'\x2', '\x2', 'N', 'Q', '\x3', '\x2', '\x2', '\x2', 'O', 'M', '\x3', '\x2', 
		'\x2', '\x2', 'O', 'P', '\x3', '\x2', '\x2', '\x2', 'P', 'R', '\x3', '\x2', 
		'\x2', '\x2', 'Q', 'O', '\x3', '\x2', '\x2', '\x2', 'R', 'T', '\x5', '\x10', 
		'\t', '\x2', 'S', 'U', '\a', ' ', '\x2', '\x2', 'T', 'S', '\x3', '\x2', 
		'\x2', '\x2', 'T', 'U', '\x3', '\x2', '\x2', '\x2', 'U', ']', '\x3', '\x2', 
		'\x2', '\x2', 'V', 'W', '\a', '\a', '\x2', '\x2', 'W', 'X', '\a', '\xE', 
		'\x2', '\x2', 'X', 'Y', '\a', '\x16', '\x2', '\x2', 'Y', 'Z', '\x5', '\f', 
		'\a', '\x2', 'Z', '[', '\a', ' ', '\x2', '\x2', '[', ']', '\x3', '\x2', 
		'\x2', '\x2', '\\', '-', '\x3', '\x2', '\x2', '\x2', '\\', '\x37', '\x3', 
		'\x2', '\x2', '\x2', '\\', '\x41', '\x3', '\x2', '\x2', '\x2', '\\', '\x44', 
		'\x3', '\x2', '\x2', '\x2', '\\', 'H', '\x3', '\x2', '\x2', '\x2', '\\', 
		'V', '\x3', '\x2', '\x2', '\x2', ']', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'^', '_', '\a', '\xE', '\x2', '\x2', '_', '`', '\a', '\x17', '\x2', '\x2', 
		'`', '\x61', '\x5', '\b', '\x5', '\x2', '\x61', '\a', '\x3', '\x2', '\x2', 
		'\x2', '\x62', '\x63', '\x5', '\n', '\x6', '\x2', '\x63', '\x64', '\a', 
		'\x18', '\x2', '\x2', '\x64', '\x66', '\x3', '\x2', '\x2', '\x2', '\x65', 
		'\x62', '\x3', '\x2', '\x2', '\x2', '\x66', 'g', '\x3', '\x2', '\x2', 
		'\x2', 'g', '\x65', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\x3', '\x2', 
		'\x2', '\x2', 'h', 'i', '\x3', '\x2', '\x2', '\x2', 'i', 'j', '\x5', '\n', 
		'\x6', '\x2', 'j', 'm', '\x3', '\x2', '\x2', '\x2', 'k', 'm', '\x5', '\n', 
		'\x6', '\x2', 'l', '\x65', '\x3', '\x2', '\x2', '\x2', 'l', 'k', '\x3', 
		'\x2', '\x2', '\x2', 'm', '\t', '\x3', '\x2', '\x2', '\x2', 'n', 'o', 
		'\a', '\b', '\x2', '\x2', 'o', 'v', '\x5', '\n', '\x6', '\x2', 'p', 'v', 
		'\a', '\xE', '\x2', '\x2', 'q', 'r', '\a', '\x14', '\x2', '\x2', 'r', 
		's', '\x5', '\b', '\x5', '\x2', 's', 't', '\a', '\x15', '\x2', '\x2', 
		't', 'v', '\x3', '\x2', '\x2', '\x2', 'u', 'n', '\x3', '\x2', '\x2', '\x2', 
		'u', 'p', '\x3', '\x2', '\x2', '\x2', 'u', 'q', '\x3', '\x2', '\x2', '\x2', 
		'v', '\v', '\x3', '\x2', '\x2', '\x2', 'w', '{', '\a', '\x14', '\x2', 
		'\x2', 'x', 'y', '\x5', '\xE', '\b', '\x2', 'y', 'z', '\a', '\x19', '\x2', 
		'\x2', 'z', '|', '\x3', '\x2', '\x2', '\x2', '{', 'x', '\x3', '\x2', '\x2', 
		'\x2', '|', '}', '\x3', '\x2', '\x2', '\x2', '}', '{', '\x3', '\x2', '\x2', 
		'\x2', '}', '~', '\x3', '\x2', '\x2', '\x2', '~', '\x7F', '\x3', '\x2', 
		'\x2', '\x2', '\x7F', '\x80', '\x5', '\xE', '\b', '\x2', '\x80', '\x81', 
		'\a', '\x15', '\x2', '\x2', '\x81', '\x90', '\x3', '\x2', '\x2', '\x2', 
		'\x82', '\x87', '\a', '\x14', '\x2', '\x2', '\x83', '\x84', '\a', '\xE', 
		'\x2', '\x2', '\x84', '\x85', '\x5', '\xE', '\b', '\x2', '\x85', '\x86', 
		'\a', '\x1A', '\x2', '\x2', '\x86', '\x88', '\x3', '\x2', '\x2', '\x2', 
		'\x87', '\x83', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', '\x3', '\x2', 
		'\x2', '\x2', '\x89', '\x87', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', 
		'\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\x3', '\x2', '\x2', '\x2', 
		'\x8B', '\x8C', '\a', '\xE', '\x2', '\x2', '\x8C', '\x8D', '\x5', '\xE', 
		'\b', '\x2', '\x8D', '\x8E', '\a', '\x15', '\x2', '\x2', '\x8E', '\x90', 
		'\x3', '\x2', '\x2', '\x2', '\x8F', 'w', '\x3', '\x2', '\x2', '\x2', '\x8F', 
		'\x82', '\x3', '\x2', '\x2', '\x2', '\x90', '\r', '\x3', '\x2', '\x2', 
		'\x2', '\x91', '\x92', '\a', '\b', '\x2', '\x2', '\x92', '\x95', '\x5', 
		'\xE', '\b', '\x2', '\x93', '\x95', '\a', '\xE', '\x2', '\x2', '\x94', 
		'\x91', '\x3', '\x2', '\x2', '\x2', '\x94', '\x93', '\x3', '\x2', '\x2', 
		'\x2', '\x95', '\xF', '\x3', '\x2', '\x2', '\x2', '\x96', '\x9A', '\a', 
		'\xE', '\x2', '\x2', '\x97', '\x99', '\x5', '\x14', '\v', '\x2', '\x98', 
		'\x97', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9C', '\x3', '\x2', '\x2', 
		'\x2', '\x9A', '\x98', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x9B', '\x3', 
		'\x2', '\x2', '\x2', '\x9B', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x9C', 
		'\x9A', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', '\a', '\x16', '\x2', 
		'\x2', '\x9E', '\xA0', '\x5', '\x18', '\r', '\x2', '\x9F', '\xA1', '\a', 
		' ', '\x2', '\x2', '\xA0', '\x9F', '\x3', '\x2', '\x2', '\x2', '\xA0', 
		'\xA1', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA2', '\x3', '\x2', '\x2', 
		'\x2', '\xA2', '\xA3', '\x5', '\x12', '\n', '\x2', '\xA3', '\x11', '\x3', 
		'\x2', '\x2', '\x2', '\xA4', '\xAA', '\a', '\t', '\x2', '\x2', '\xA5', 
		'\xA6', '\x5', '\x16', '\f', '\x2', '\xA6', '\xA7', '\a', '\x16', '\x2', 
		'\x2', '\xA7', '\xA8', '\x5', '\x18', '\r', '\x2', '\xA8', '\xA9', '\a', 
		' ', '\x2', '\x2', '\xA9', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAA', 
		'\xA5', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAC', '\x3', '\x2', '\x2', 
		'\x2', '\xAC', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAD', '\x3', 
		'\x2', '\x2', '\x2', '\xAD', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xAE', 
		'\xB0', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xA4', '\x3', '\x2', '\x2', 
		'\x2', '\xAF', '\xAE', '\x3', '\x2', '\x2', '\x2', '\xB0', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\xB1', '\xD2', '\a', '\xE', '\x2', '\x2', '\xB2', 
		'\xD2', '\a', '\n', '\x2', '\x2', '\xB3', '\xB7', '\a', '\x14', '\x2', 
		'\x2', '\xB4', '\xB5', '\x5', '\x14', '\v', '\x2', '\xB5', '\xB6', '\a', 
		'\x19', '\x2', '\x2', '\xB6', '\xB8', '\x3', '\x2', '\x2', '\x2', '\xB7', 
		'\xB4', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xB9', '\x3', '\x2', '\x2', 
		'\x2', '\xB9', '\xB7', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xBA', '\x3', 
		'\x2', '\x2', '\x2', '\xBA', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xBB', 
		'\xBC', '\x5', '\x14', '\v', '\x2', '\xBC', '\xBD', '\a', '\x15', '\x2', 
		'\x2', '\xBD', '\xD2', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBF', '\a', 
		'\x14', '\x2', '\x2', '\xBF', '\xC0', '\a', '\xE', '\x2', '\x2', '\xC0', 
		'\xC1', '\x5', '\x14', '\v', '\x2', '\xC1', '\xC2', '\a', '\x15', '\x2', 
		'\x2', '\xC2', '\xD2', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC4', '\a', 
		'\x1B', '\x2', '\x2', '\xC4', '\xD2', '\a', '\x1C', '\x2', '\x2', '\xC5', 
		'\xC9', '\a', '\x14', '\x2', '\x2', '\xC6', '\xC7', '\x5', '\x14', '\v', 
		'\x2', '\xC7', '\xC8', '\a', '\x1E', '\x2', '\x2', '\xC8', '\xCA', '\x3', 
		'\x2', '\x2', '\x2', '\xC9', '\xC6', '\x3', '\x2', '\x2', '\x2', '\xCA', 
		'\xCB', '\x3', '\x2', '\x2', '\x2', '\xCB', '\xC9', '\x3', '\x2', '\x2', 
		'\x2', '\xCB', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xCD', '\x3', 
		'\x2', '\x2', '\x2', '\xCD', '\xCE', '\x5', '\x14', '\v', '\x2', '\xCE', 
		'\xCF', '\a', '\x15', '\x2', '\x2', '\xCF', '\xD2', '\x3', '\x2', '\x2', 
		'\x2', '\xD0', '\xD2', '\a', '\r', '\x2', '\x2', '\xD1', '\xB1', '\x3', 
		'\x2', '\x2', '\x2', '\xD1', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xD1', 
		'\xB3', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xBE', '\x3', '\x2', '\x2', 
		'\x2', '\xD1', '\xC3', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xC5', '\x3', 
		'\x2', '\x2', '\x2', '\xD1', '\xD0', '\x3', '\x2', '\x2', '\x2', '\xD2', 
		'\x15', '\x3', '\x2', '\x2', '\x2', '\xD3', '\xF1', '\a', '\xE', '\x2', 
		'\x2', '\xD4', '\xF1', '\a', '\n', '\x2', '\x2', '\xD5', '\xD9', '\a', 
		'\x14', '\x2', '\x2', '\xD6', '\xD7', '\x5', '\x16', '\f', '\x2', '\xD7', 
		'\xD8', '\a', '\x19', '\x2', '\x2', '\xD8', '\xDA', '\x3', '\x2', '\x2', 
		'\x2', '\xD9', '\xD6', '\x3', '\x2', '\x2', '\x2', '\xDA', '\xDB', '\x3', 
		'\x2', '\x2', '\x2', '\xDB', '\xD9', '\x3', '\x2', '\x2', '\x2', '\xDB', 
		'\xDC', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xDD', '\x3', '\x2', '\x2', 
		'\x2', '\xDD', '\xDE', '\x5', '\x16', '\f', '\x2', '\xDE', '\xDF', '\a', 
		'\x15', '\x2', '\x2', '\xDF', '\xF1', '\x3', '\x2', '\x2', '\x2', '\xE0', 
		'\xE1', '\a', '\x14', '\x2', '\x2', '\xE1', '\xE2', '\a', '\xE', '\x2', 
		'\x2', '\xE2', '\xE3', '\x5', '\x16', '\f', '\x2', '\xE3', '\xE4', '\a', 
		'\x15', '\x2', '\x2', '\xE4', '\xF1', '\x3', '\x2', '\x2', '\x2', '\xE5', 
		'\xE9', '\a', '\x14', '\x2', '\x2', '\xE6', '\xE7', '\x5', '\x16', '\f', 
		'\x2', '\xE7', '\xE8', '\a', '\x1E', '\x2', '\x2', '\xE8', '\xEA', '\x3', 
		'\x2', '\x2', '\x2', '\xE9', '\xE6', '\x3', '\x2', '\x2', '\x2', '\xEA', 
		'\xEB', '\x3', '\x2', '\x2', '\x2', '\xEB', '\xE9', '\x3', '\x2', '\x2', 
		'\x2', '\xEB', '\xEC', '\x3', '\x2', '\x2', '\x2', '\xEC', '\xED', '\x3', 
		'\x2', '\x2', '\x2', '\xED', '\xEE', '\x5', '\x16', '\f', '\x2', '\xEE', 
		'\xEF', '\a', '\x15', '\x2', '\x2', '\xEF', '\xF1', '\x3', '\x2', '\x2', 
		'\x2', '\xF0', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xF0', '\xD4', '\x3', 
		'\x2', '\x2', '\x2', '\xF0', '\xD5', '\x3', '\x2', '\x2', '\x2', '\xF0', 
		'\xE0', '\x3', '\x2', '\x2', '\x2', '\xF0', '\xE5', '\x3', '\x2', '\x2', 
		'\x2', '\xF1', '\x17', '\x3', '\x2', '\x2', '\x2', '\xF2', '\xF3', '\x5', 
		'\x1A', '\xE', '\x2', '\xF3', '\xF4', '\a', '\x1E', '\x2', '\x2', '\xF4', 
		'\xF5', '\x5', '\x18', '\r', '\x2', '\xF5', '\xF8', '\x3', '\x2', '\x2', 
		'\x2', '\xF6', '\xF8', '\x5', '\x1A', '\xE', '\x2', '\xF7', '\xF2', '\x3', 
		'\x2', '\x2', '\x2', '\xF7', '\xF6', '\x3', '\x2', '\x2', '\x2', '\xF8', 
		'\x19', '\x3', '\x2', '\x2', '\x2', '\xF9', '\xFA', '\b', '\xE', '\x1', 
		'\x2', '\xFA', '\xFB', '\x5', '\x1C', '\xF', '\x2', '\xFB', '\x104', '\x3', 
		'\x2', '\x2', '\x2', '\xFC', '\xFD', '\f', '\x5', '\x2', '\x2', '\xFD', 
		'\xFE', '\a', '\x11', '\x2', '\x2', '\xFE', '\x103', '\x5', '\x1C', '\xF', 
		'\x2', '\xFF', '\x100', '\f', '\x4', '\x2', '\x2', '\x100', '\x101', '\a', 
		'\x12', '\x2', '\x2', '\x101', '\x103', '\x5', '\x1C', '\xF', '\x2', '\x102', 
		'\xFC', '\x3', '\x2', '\x2', '\x2', '\x102', '\xFF', '\x3', '\x2', '\x2', 
		'\x2', '\x103', '\x106', '\x3', '\x2', '\x2', '\x2', '\x104', '\x102', 
		'\x3', '\x2', '\x2', '\x2', '\x104', '\x105', '\x3', '\x2', '\x2', '\x2', 
		'\x105', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x106', '\x104', '\x3', 
		'\x2', '\x2', '\x2', '\x107', '\x108', '\b', '\xF', '\x1', '\x2', '\x108', 
		'\x109', '\x5', '\x1E', '\x10', '\x2', '\x109', '\x10F', '\x3', '\x2', 
		'\x2', '\x2', '\x10A', '\x10B', '\f', '\x4', '\x2', '\x2', '\x10B', '\x10C', 
		'\a', '\x13', '\x2', '\x2', '\x10C', '\x10E', '\x5', '\x1E', '\x10', '\x2', 
		'\x10D', '\x10A', '\x3', '\x2', '\x2', '\x2', '\x10E', '\x111', '\x3', 
		'\x2', '\x2', '\x2', '\x10F', '\x10D', '\x3', '\x2', '\x2', '\x2', '\x10F', 
		'\x110', '\x3', '\x2', '\x2', '\x2', '\x110', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '\x111', '\x10F', '\x3', '\x2', '\x2', '\x2', '\x112', '\x114', 
		'\x5', ' ', '\x11', '\x2', '\x113', '\x115', '\x5', ' ', '\x11', '\x2', 
		'\x114', '\x113', '\x3', '\x2', '\x2', '\x2', '\x115', '\x116', '\x3', 
		'\x2', '\x2', '\x2', '\x116', '\x114', '\x3', '\x2', '\x2', '\x2', '\x116', 
		'\x117', '\x3', '\x2', '\x2', '\x2', '\x117', '\x11A', '\x3', '\x2', '\x2', 
		'\x2', '\x118', '\x11A', '\x5', ' ', '\x11', '\x2', '\x119', '\x112', 
		'\x3', '\x2', '\x2', '\x2', '\x119', '\x118', '\x3', '\x2', '\x2', '\x2', 
		'\x11A', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x11B', '\x139', '\a', '\r', 
		'\x2', '\x2', '\x11C', '\x11F', '\a', '\xE', '\x2', '\x2', '\x11D', '\x11E', 
		'\a', '\x17', '\x2', '\x2', '\x11E', '\x120', '\x5', '\b', '\x5', '\x2', 
		'\x11F', '\x11D', '\x3', '\x2', '\x2', '\x2', '\x11F', '\x120', '\x3', 
		'\x2', '\x2', '\x2', '\x120', '\x139', '\x3', '\x2', '\x2', '\x2', '\x121', 
		'\x139', '\a', '\xF', '\x2', '\x2', '\x122', '\x139', '\a', '\v', '\x2', 
		'\x2', '\x123', '\x124', '\a', '\x14', '\x2', '\x2', '\x124', '\x125', 
		'\x5', '\x18', '\r', '\x2', '\x125', '\x126', '\a', '\x15', '\x2', '\x2', 
		'\x126', '\x139', '\x3', '\x2', '\x2', '\x2', '\x127', '\x12D', '\a', 
		'\x1B', '\x2', '\x2', '\x128', '\x129', '\x5', '\x18', '\r', '\x2', '\x129', 
		'\x12A', '\a', '\x1D', '\x2', '\x2', '\x12A', '\x12C', '\x3', '\x2', '\x2', 
		'\x2', '\x12B', '\x128', '\x3', '\x2', '\x2', '\x2', '\x12C', '\x12F', 
		'\x3', '\x2', '\x2', '\x2', '\x12D', '\x12B', '\x3', '\x2', '\x2', '\x2', 
		'\x12D', '\x12E', '\x3', '\x2', '\x2', '\x2', '\x12E', '\x131', '\x3', 
		'\x2', '\x2', '\x2', '\x12F', '\x12D', '\x3', '\x2', '\x2', '\x2', '\x130', 
		'\x132', '\x5', '\x18', '\r', '\x2', '\x131', '\x130', '\x3', '\x2', '\x2', 
		'\x2', '\x131', '\x132', '\x3', '\x2', '\x2', '\x2', '\x132', '\x133', 
		'\x3', '\x2', '\x2', '\x2', '\x133', '\x136', '\a', '\x1C', '\x2', '\x2', 
		'\x134', '\x135', '\a', '\x17', '\x2', '\x2', '\x135', '\x137', '\x5', 
		'\b', '\x5', '\x2', '\x136', '\x134', '\x3', '\x2', '\x2', '\x2', '\x136', 
		'\x137', '\x3', '\x2', '\x2', '\x2', '\x137', '\x139', '\x3', '\x2', '\x2', 
		'\x2', '\x138', '\x11B', '\x3', '\x2', '\x2', '\x2', '\x138', '\x11C', 
		'\x3', '\x2', '\x2', '\x2', '\x138', '\x121', '\x3', '\x2', '\x2', '\x2', 
		'\x138', '\x122', '\x3', '\x2', '\x2', '\x2', '\x138', '\x123', '\x3', 
		'\x2', '\x2', '\x2', '\x138', '\x127', '\x3', '\x2', '\x2', '\x2', '\x139', 
		'!', '\x3', '\x2', '\x2', '\x2', '%', '#', '(', '\x32', '<', 'O', 'T', 
		'\\', 'g', 'l', 'u', '}', '\x89', '\x8F', '\x94', '\x9A', '\xA0', '\xAC', 
		'\xAF', '\xB9', '\xCB', '\xD1', '\xDB', '\xEB', '\xF0', '\xF7', '\x102', 
		'\x104', '\x10F', '\x116', '\x119', '\x11F', '\x12D', '\x131', '\x136', 
		'\x138',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
